src/Django/scode/judge/urls.py
from django.conf.urls import url
from django.contrib import admin

from judge.views import *

urlpatterns = [
    # example : /professor
    url(r'^professor$', ProfessorMainLV.as_view(), name='professor'),

    # example : /professor/python_01
    url(r'^professor/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/$', ProfessorSubjectLV.as_view(), name='subject'),

    # example : /professor/python_01/add
    url(r'^professor/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/add/$', ProfessorCreateView.as_view(), name='add'),

    # example : /professor/python_01/update
    url(r'^professor/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/update/$', ProfessorUpdateView.as_view(), name='update'),

    # example : /professor/python_01/delete
    url(r'^professor/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/delete/$', ProfessorDeleteView.as_view(), name='delete'),

    # example : /professor/python_01/settings
    url(r'^professor/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/settings/$', ProfessorSettingsView.as_view(), name='settings'),

    # example : /professor/python_01/3
    url(r'^professor/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/(?P<sequence>[0-9]+)/$', ProfessorResultLV.as_view(), name='result'),

    # example : /student
    url(r'^student$', StudentMainLV.as_view(), name='student'),

    # example : /student/python_01
    url(r'^student/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/$', StudentSubjectLV.as_view(), name='std_subject'),

    # example : /student/python_01/3
    url(r'^student/(?P<subject_title>[a-zA-Z0-9]+)_(?P<classes>[0-9][0-9])/(?P<assign_no>[1-9][0-9]*)/$', StudentAssignment.as_view(), name='std_assign'),
]

src/Django/scode/scode/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from scode.views import HomeView, LoginView, LogoutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),

    url(r'^judge/', include(('judge.urls', 'judge'), namespace='judge')),

    url(r'^$', HomeView.as_view(), name='home'),
]

src/Django/scode/judge/forms.py
from django import forms

class AssignmentForm(forms.Form):
    assignment_name = forms.CharField(label="assignment_name")
    assignment_desc = forms.CharField(label="assignment_desc", widget=forms.Textarea)
    deadline = forms.IntegerField(label="deadline", initial=7)
    in_file = forms.FileField(label="in_file")
    out_file = forms.FileField(label="out_file")

class CodingForm(forms.Form):
    code = forms.CharField(widget=forms.Textarea(), label="code")

class LoginForm(forms.Form):
    userid = forms.CharField(label="userid")
    password = forms.CharField(label="password", widget=forms.PasswordInput)

src/Django/scode/judge/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.views.generic.base import TemplateView
#from .forms import PostForm

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from django.db import connection

from judge.models import *
from judge.forms import AssignmentForm, CodingForm


from judge.judgeManager import JudgeManager
from scode.loginManager import LoginManager

import pymysql
import os
import datetime


#-- Here is developing area
# This page shows a list of subjects that professor has.
class ProfessorMainLV(ListView, LoginManager):
    queryset = None
    template_name = 'judge/professor/professor_main_list.html'

    def get(self, request, *args, **kwargs):
        sql = 'SELECT judge_professor.professor_id,title,classes, judge_subject.pri_key as subject_id \
           FROM judge_professor , judge_subject_has_professor, judge_subject \
           WHERE judge_professor.professor_id=judge_subject_has_professor.professor_id \
           AND judge_subject.pri_key=judge_subject_has_professor.sub_seq_id \
           AND judge_professor.professor_id=' + request.session["professor_id"] + ' \
           ORDER BY judge_subject.title;'

        subject_list_sql = professor.objects.raw(sql)

        return render(request, self.template_name, {'subject_list_sql': subject_list_sql})

# This page shows a list of assignment in selected subject
class ProfessorSubjectLV(ListView, LoginManager):
    #It doesn't used.
    queryset = None

    template_name = 'judge/professor/professor_subject_list.html'
    paginate_by = 10

    def common(self, request):
        if request.session['subject_id']:
            sql = 'SELECT * \
                    FROM judge_subject_has_professor, judge_professor, judge_assignment, judge_subject \
                    WHERE judge_subject_has_professor.sub_seq_id = judge_assignment.sub_seq_id \
                    AND judge_professor.professor_id = judge_subject_has_professor.professor_id \
                    AND judge_subject.pri_key = judge_subject_has_professor.sub_seq_id \
                    AND judge_subject.pri_key = "{0}" \
                    AND judge_professor.professor_id = "{1}" \
                    ORDER BY judge_subject.title;'.format(request.session['subject_id'], request.session['professor_id'])

            subject_list_sql = professor.objects.raw(sql)

            return render(request, self.template_name, { 'subject_list_sql': subject_list_sql})

        else:
            return HttpResponse('This is wrong way!')

    def get(self, request, *args, **kwargs):
        return self.common(request)


    def post(self, request, *args, **kwargs):
        form = request.POST
        request.session['title'] = form.get('title')
        request.session['classes'] = form.get('classes')
        request.session['subject_id'] = form.get('subject_id')

        return self.common(request)

# This page shows result of a assiginment.
class ProfessorResultLV(ListView, LoginManager):
    # We need to revise sub_seq_id
    sub_seq_id = 2
    sql = 'SELECT judge_student.student_id,judge_student.student_name,score \
            FROM judge_student,judge_submit,judge_assignment \
            WHERE judge_assignment.sub_seq_id = judge_submit.sub_seq_id \
            AND judge_student.student_id = judge_submit.student_id \
            AND judge_assignment.sequence = judge_submit.sequence_id \
            AND judge_submit.sub_seq_id = ' + str(sub_seq_id) + ';'

    queryset = student.objects.raw(sql)
    template_name = 'judge/professor/professor_result_list.html'
    context_object_name = "objects"

class ProfessorCreateView(FormView, LoginManager):
    template_name = 'judge/professor/professor_assignment_add.html'
    form_class = AssignmentForm

#    def form_valid(self, form):
        #return render(self.request, self.template_name, {'form': self.form})
#        return super().form_valid(form)

    def handle_uploaded_file(self, files, path):
        uploaded_file_name = ['in', 'out']
        for f in files:
            with open(path + '/temp/' + uploaded_file_name[files.index(f)], 'wb+') as dest:
                for chunk in f.chunks():
                    dest.write(chunk)

    def post(self, request, *args, **kwargs):
        judgeManager = JudgeManager()
        judgeManager.construct(request.session['professor_id'])
        base_file_path = judgeManager.get_file_path(request.session['subject_id'], request.session['professor_id'])
        self.handle_uploaded_file([request.FILES['in_file'], request.FILES['out_file']], base_file_path)

        #judgeManager.create_problem(request.session['professor_id'], request.session['subject_id'])
        judgeManager.add_assignment(request.session['subject_id'], request.POST.get('assignment_name'),
                request.POST.get('assignment_desc'), int(request.POST.get('deadline')))


        # we need next step which is inserting db.

        return redirect(reverse_lazy('judge:subject', args=[request.session['title'], request.session['classes']]))


#class ProfessorUpdateView(UpdateView):
class ProfessorUpdateView(TemplateView, LoginManager):
    template_name = 'judge/professor/professor_assignment_update.html'

#class ProfessorDeleteView(DeleteView):
class ProfessorDeleteView(TemplateView, LoginManager):
    template_name = 'judge/professor/professor_assignment_delete.html'

#class ProfessorSettingsView(UpdateView):
class ProfessorSettingsView(TemplateView, LoginManager):
    template_name = 'judge/professor/professor_subject_settings.html'


#-- student
class StudentMainLV(ListView, LoginManager):
	queryset = None
	template_name = 'judge/student/student_main_list.html'
	
	def get(self, request, *args, **kwargs):
	    sql = 'SELECT judge_student.student_id as student_id, title, classes, judge_subject.pri_key as subject_id \
                FROM judge_subject, judge_signup_class, judge_student \
                WHERE judge_subject.pri_key = judge_signup_class.sub_seq_id \
                AND judge_signup_class.student_id = judge_student.student_id \
                AND judge_student.student_id = "{0}" \
                ORDER BY judge_subject.title;'.format(request.session['student_id'])
		
	    subject_list_sql = student.objects.raw(sql)

	    return render(request, self.template_name, {'subject_list_sql': subject_list_sql})

class StudentSubjectLV(TemplateView, LoginManager):
	queryset = None
	template_name = 'judge/student/student_subject_list.html'

        def common(self, request):
	    if request.session['subject_id']:
                now = datetime.datetime.now()

                common_sql = ' \
                    SELECT sequence, assignment_name, lf.student_id, deadline, score, max_score \
                    FROM ( \
                    SELECT sequence, assignment_name, judge_student.student_id, deadline, max_score, judge_assignment.sub_seq_id \
                    FROM judge_student \
                    INNER JOIN (judge_signup_class, judge_assignment) \
                    ON (judge_student.student_id = judge_signup_class.student_id \
                    AND judge_signup_class.sub_seq_id = judge_assignment.sub_seq_id) \
                    WHERE judge_assignment.sub_seq_id = {0} \
                    AND judge_student.student_id = "{1}" \
                    AND judge_assignment.sub_seq_id = {0}) as lf \
                    LEFT JOIN judge_submit \
                    ON (lf.sequence = judge_submit.sequence_id \
                    AND lf.student_id = judge_submit.student_id \
                    AND lf.sub_seq_id = judge_submit.sub_seq_id) \
                    WHERE deadline '.format(request.session["subject_id"], request.session['student_id'])

                not_expired_assignment_list_sql = common_sql + '> "{0}";'.format(now)
                expired_assignment_list_sql = common_sql + '< "{0}";'.format(now)

                not_expired_assignment_list = student.objects.raw(not_expired_assignment_list_sql)
                expired_assignment_list = student.objects.raw(expired_assignment_list_sql)

        	return render(request, self.template_name,
                    { 'not_expired_assignment_list': not_expired_assignment_list,
                      'expired_assignment_list': expired_assignment_list })
            else:
                return HttpResponse('This is wrong way!')


	def get(self, request, *args, **kwargs):
            return self.common(request)

	def post(self, request, *args, **kwargs):
	    form = request.POST
	    request.session['title'] = form.get('title')
	    request.session['classes'] = form.get('classes')
	    request.session['subject_id'] = form.get('subject_id')

            return self.common(request)

class StudentAssignment(FormView, LoginManager):
    template_name = 'judge/student/student_assignment.html'
    form_class = CodingForm

    def post(self, request, *args, **kwargs):
        judgeManager = JudgeManager()
        sequence = request.POST.get('sequence')
        
        # into assignment page
        if sequence:
            lang_name = judgeManager.get_lang_name(
                    judgeManager.get_lang_pri_key(request.session['subject_id']))
            assign_info = { 
                'lang': lang_name, 
                'name': judgeManager.get_assign_name(request.session['subject_id'], sequence), 
                'desc': judgeManager.get_assign_desc(request.session['subject_id'], sequence) 
            }
            request.session['sequence'] = sequence
            return render(request, self.template_name, {'assign_info': assign_info, 'form': CodingForm})

        # submit assignment
        else:
            judgeManager = JudgeManager()

src/Django/scode/judge/templates/judge/student/student_assignment.html
{% extends "base.html" %}

{% block title %}student_assignment.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">

        <form action="." method="post">{% csrf_token %}

                {% if form.errors %}
                <p class="errornote">Wrong! Please correct the error(s) below.</p>
                {% endif %}

                <fieldset class="aligned">
                        <div class="form-row">
				lang {{ assign_info.lang }}
                        </div>
                        <div class="form-row">
				assign_name {{ assign_info.name }}
                        </div>
                        <div class="form-row">
				desc {{ assign_info.desc }}
                        </div>
                        <div class="form-row">
                                {{ form.code.label_tag }} {{ form.code }}
                        </div>
                </fieldset>


                <div class="submit-row">
                        <input type="submit" value="Submit"/>
                </div>
                <script type="text/javascript">document.getElementById('id_code').focus();</script>

</div>
{% endblock content %}

src/Django/scode/judge/templates/judge/student/student_main_list.html
{% extends "base.html" %}

{% block title %}student_main_list.html{% endblock %}

{% block content %}
<div id="content">
	<h1>Welcome, {{ request.session.name }}({{ request.session.student_id }})!</h1>
	<table>
		<tr>
			<th>title</th>
		</tr>

		{% for obj in subject_list_sql %}
		<tr>
			<td>
				<form id='{{ obj.title }}_{{ obj.classes}}' method="post" action="{% url 'judge:std_subject' obj.title obj.classes %}">{% csrf_token %}
					<input type="hidden" name="title" value="{{ obj.title }}"/>
					<input type="hidden" name="classes" value="{{ obj.classes }}"/>
					<input type="hidden" name="subject_id" value="{{ obj.subject_id }}"/>
					<a href="javascript:{}" onclick=document.getElementById("{{ obj.title }}_{{ obj.classes }}").submit();>{{ obj.title }}_{{ obj.classes }}</a>
				</form>
			</td>
		</tr>
		{% endfor %}


	</table>

</div>
{% endblock content %}

src/Django/scode/judge/templates/judge/student/student_subject_list.html
{% extends "base.html" %}

{% block title %}student_subject_list.html{% endblock %}

{% block content %}
<div id="content">
	<h1> {{ request.session.title }}_{{ request.session.classes}} </h1>
	<table>
		<tr>
			<th>sequence</th>
			<th>assginment_name</th>
			<th>deadline</th>
			<th>state</th>
			<th>score</th>
		</tr>

		{% for obj in expired_assignment_list %}
		<tr>
			<td>{{ obj.sequence }}</td>
			<td>{{ obj.assignment_name }}</td>
			{% comment %} datetime format reference : https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#date {% endcomment%}
			<td>{{ obj.deadline | date:"Y-m-d(D)" }} {{ obj.deadline | time:"H:i:s" }}</td>
			<td>expired</td>
			<td>{% if obj.score %}
				{{ obj.score }}
			    {% else %}
				0
			    {% endif %}
			    &nbsp / &nbsp {{ obj.max_score }}
			</td>

		</tr>
		{% endfor %}

		{% for obj in not_expired_assignment_list %}
		<tr>
			<td>{{ obj.sequence }}</td>

			<td>
				<form id='{{ obj.sequence }}' method="post" action="{% url 'judge:std_assign' request.session.title request.session.classes obj.sequence%}">{% csrf_token %}
					<input type="hidden" name="sequence" value="{{ obj.sequence }}"/>
					<a href="javascript:{}" onclick=document.getElementById("{{ obj.sequence }}").submit();>{{ obj.assignment_name }}</a>
				</form>
			</td>
			<td>{{ obj.deadline | date:"Y-m-d(D)" }} {{ obj.deadline | time:"H:i:s" }}</td>
			<td>working</td>
			<td>{% if obj.score %}
				{{ obj.score }}
			    {% else %}
				0
			    {% endif %}
			    &nbsp / &nbsp {{ obj.max_score }}
			</td>

		</tr>
		{% endfor %}

	</table>

</div>
{% endblock content %}